---
layout: cv
title: Gabriel Guerrero
---
Expertise in leveraging data to drive sustainable growth and operational efficiency.
Technical Skills: Python, R, SQL, Tableau, Power BI, SAP, Google Cloud Platform, Microsoft Azure, HTML, CSS, JS.

<div id="webaddress">
<a href="gguerrero@byui.edu">| gabrrielguerrero@byui.edu</a>
<a href="guerrero.gjp@gmail.com">| guerrero.gjp@gmail.com</a>
<a href="https://github.com/josegabrielguerrero26">| Github</a>
</div>


## PROFESSIONAL EXPERIENCE
- Sr Manager Data & Business Analytics, Hertz Global Holding | Jul 2020 – Present
- Director of Operations & Supply Chain, La Europea SA de CV, Spain-Mexico | Jul 2018 – Jul 2020
- Sr. Continuous Improvement Manager, Sleep Number Corp, USA | Jun 2017 – Jun 2018
- Project Manager, Utah Valley University, USA | Jan 2016- Jun 2017


### Specialized in

•	Expertise in leveraging data to drive sustainable growth and operational efficiency.


### Technical Skills

• Python, R, SQL, Tableau, Power BI, SAP, Google Cloud Platform, Microsoft Azure, HTML, CSS, JS.


## Education

`B.Sc. in Information Technology, Data Science`
__Brigham Young University__

`B.Sc. in Operations & Supply Chain Management`
__Brigham Young University__



<!-- ### Footer

Last updated: Fall 2024 -->